# These are supported funding model platforms

github: Lunatixz
patreon: pseudotv
open_collective: pseudotv-live
custom: [Paypal](https://paypal.me/Lunatixz), [Coffee ☕](https://www.buymeacoffee.com/Lunatixz)
