# These are supported funding model platforms

github: Lunatixz
patreon: pseudotv
open_collective: Lunatixz
custom: ["https://paypal.me/Lunatixz", paypal.me]
custom: ["https://www.buymeacoffee.com/Lunatixz", buymeacoffee.com]
